name: pythia_windows
description: Pythia Windows client.
publish_to: "none"
version: 1.0.0+100

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  crypto: ^3.0.6
  path_provider: ^2.1.4
  file_selector: ^1.1.0
  archive: ^3.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pythia-plugin-runner.cjs
