#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
controls="$root/Pythia/Views/Controls.swift"
settings="$root/Pythia/Views/SettingsWindowController.swift"
translator="$root/Pythia/Views/TranslatorWindowController.swift"
checker="$root/Pythia/Services/PythiaUpdateChecker.swift"
installer="$root/Pythia/Services/PythiaUpdateInstaller.swift"
plugins="$root/Pythia/Services/PluginManager.swift"
ocr="$root/Pythia/Services/OCRService.swift"
selection="$root/Pythia/Services/SelectionReader.swift"
credentials="$root/Pythia/Stores/LocalCredentialStore.swift"
macos_plugin_runner="$root/Pythia/Resources/pythia-plugin-runner.cjs"
windows_plugin_runner="$root/Windows/Pythia.Windows/assets/pythia-plugin-runner.cjs"

# PillButton intentionally uses the native AppKit renderer so macOS 27 can
# supply the system appearance instead of a layer-painted custom button.
grep -q 'isBordered = true' "$controls"
grep -q 'bezelStyle = .rounded' "$controls"
grep -q 'contentTintColor = theme' "$controls"
grep -q 'mouseEntered(with event' "$controls"
grep -q 'isHovering ? hoverFill' "$controls"
! grep -q 'enhancedGlass' "$controls"
! grep -q 'transparentCheckbox' "$settings"
! grep -q 'backgroundView?.enhancedGlass' "$translator"
grep -q '/releases?per_page=' "$checker"
grep -q 'PythiaReleaseVersionPolicy' "$checker"
grep -q 'isBareReturn && hadMarkedText' "$controls"
grep -q 'contentView.scroll(to: .zero)' "$controls"
grep -q 'AutomaticLanguagePolicy.targetLanguage' "$translator"
grep -q 'compactServicePicker.reloadOptions' "$translator"
grep -q 'expandCompactWindow' "$translator"
grep -q 'compactTranslationWindow' "$settings"
grep -q 'customLLMEndpoint' "$root/Pythia/Services/TranslationService.swift"
grep -q 'anthropic-version' "$root/Pythia/Services/TranslationService.swift"
grep -q 'TranslationChunkPolicy.chunks' "$root/Pythia/Services/TranslationService.swift"
grep -q 'requestTimeout: 300, resourceTimeout: 300' "$root/Pythia/Services/TranslationService.swift"
grep -q 'TranslationRetryPolicy.retryDelay' "$root/Pythia/Services/TranslationService.swift"
grep -q 'setResult("已取消"' "$translator"
grep -q 'TranslationChunkPolicy.swift in Sources' "$root/Pythia.xcodeproj/project.pbxproj"
grep -q 'CGPreflightScreenCaptureAccess' "$ocr"
grep -q 'CGRequestScreenCaptureAccess' "$ocr"
grep -q 'Pythia-Screenshot-' "$ocr"
grep -q 'com.kingsoft.wpsoffice.mac' "$selection"
grep -q 'hasPrefix("com.kingsoft.wpsoffice.mac.")' "$selection"
grep -q 'readClipboardFallback(targetApplication: target)' "$selection"
grep -q 'restorePasteboard(original, to: pasteboard)' "$selection"
! grep -q '无法截取屏幕。请确认屏幕录制权限。' "$ocr"
grep -q 'guard hasPresentedWindow, !isApplyingWindowPlacement' "$translator"
grep -q 'scheduleResultHeightRefresh()' "$translator"
grep -q 'let contentSize = NSSize(width: 300' "$controls"
grep -q 'controller.preferredContentSize = contentSize' "$controls"
grep -q 'popover.contentSize = contentSize' "$controls"
grep -q 'preserveOriginalPackage: false' "$plugins"
grep -q 'migrationPolicy.*legacy-package-not-retained' "$plugins"
grep -q 'removeItem(at: retainedLegacy)' "$plugins"
grep -q 'Pythia 不保留旧插件或 .potext 备份' "$settings"
grep -q 'PythiaSourceRevision' "$settings"
grep -q 'Record source revision' "$root/Pythia.xcodeproj/project.pbxproj"
grep -q 'NSStackView(views: \[githubButton, checkButton\])' "$settings"
grep -q 'showAvailableUpdate(_ info: PythiaUpdateInfo)' "$translator"
grep -q 'self.translator.showAvailableUpdate(info)' "$root/Pythia/App/PythiaAppDelegate.swift"
grep -q 'PYTHIA_UPDATE_RELEASES_URL' "$root/Pythia/Services/PythiaUpdateChecker.swift"
grep -q 'case installed(app: URL, rollback: URL?)' "$installer"
grep -q 'guard activity == .idle else' "$installer"
grep -q 'guard activity == .downloaded else' "$installer"
grep -q 'Pythia-old-' "$installer"
grep -q 'remained alive for a' "$installer"
grep -q '/bin/sleep 8' "$installer"
grep -q 'awk -v exe=' "$installer"
grep -q '/bin/mv "$3" "$2"' "$installer"
grep -q '下载并安装 Pythia \\(info.latestVersion)' "$translator"
grep -q 'private func scheduleAutosave()' "$settings"
grep -q 'settings?.flushPendingAutosave()' "$root/Pythia/App/PythiaAppDelegate.swift"
grep -q 'func flushPendingAutosave()' "$settings"
grep -q 'message: "\\(title)：\\(message)"' "$root/Pythia/Views/HistoryWindowController.swift"
grep -q 'macOS-14%2B' "$root/README.md"
if grep -q 'PillButton("保存"' "$settings"; then
  echo "settings must autosave without a global Save button" >&2
  exit 1
fi
test ! -e "$root/Pythia/Stores/SecureCredentialStore.swift"
grep -q 'posixPermissions: 0o700' "$credentials"
grep -q 'posixPermissions: 0o600' "$credentials"
! grep -R -qE '^[[:space:]]*import (Security|LocalAuthentication)|SecItem(CopyMatching|Add|Update|Delete)|kSecClass' "$root/Pythia"
cmp -s "$macos_plugin_runner" "$windows_plugin_runner"
grep -q 'nativeRequest' "$macos_plugin_runner"
grep -q 'Math.min(timeoutMs, 180000)' "$macos_plugin_runner"

echo "macOS UI contracts passed"
